process {
    executor = 'slurm'
    clusterOptions = '--qos=normal'
    queue = 'amilan'
    module = 'qiime2/2026.1_amplicon'
    cpus = 6
    memory = { 3840.MB * task.cpus }
    time = '2h'
    errorStrategy = 'finish'
    maxForks = 1 // qiime passes a single file to each step. increase this in non-qiime2 processes if needed

    withName: 'FASTP' {
        cpus = 2
        time = '1m'
        maxForks = 10
    }

    withName: 'DENOISE' {
        cpus = 24
        time = '1h'
    }

}
executor {
    queueSize = 20
    submitRateLimit = '5/1min'
}
